// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAonkccD3u4cWXe_DmR8xMTxXVk1K_PCvA',
    appId: '1:149980039369:web:6c0960e27422b2430aa518',
    messagingSenderId: '149980039369',
    projectId: 'gameapp-594c5',
    authDomain: 'gameapp-594c5.firebaseapp.com',
    storageBucket: 'gameapp-594c5.appspot.com',
    measurementId: 'G-2GZ6QM8EB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDubrGxzgEd64vO-FeFjY1wKfucvSPEyJw',
    appId: '1:149980039369:android:1f543547eac5842b0aa518',
    messagingSenderId: '149980039369',
    projectId: 'gameapp-594c5',
    storageBucket: 'gameapp-594c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI8gtMdWlHijcxswLfQd_SXc9YZoTKCwo',
    appId: '1:149980039369:ios:a5badd904e067faa0aa518',
    messagingSenderId: '149980039369',
    projectId: 'gameapp-594c5',
    storageBucket: 'gameapp-594c5.appspot.com',
    iosClientId: '149980039369-mi8d3e6prasblj8g40pnqodutbr3ua1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamapp',
  );
}
